# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci --ignore-scripts

# Copy source
COPY src ./src

# Build
RUN npm run build

# Runtime stage
FROM node:lts-alpine
WORKDIR /app

# Copy only production deps
COPY package.json package-lock.json ./
RUN npm ci --production --ignore-scripts

# Copy build output
COPY --from=builder /app/build ./build

# Create output dir
RUN mkdir -p /app/output

# Entrypoint
ENTRYPOINT ["node", "build/index.js"]
CMD []
